### PR TITLE
update-blog: add cchardet dependency

### PR DESCRIPTION
**Pull request by lukegb**
aiohttp will use cchardet to determine the charset of the page it
retrieves if it's available and isn't specified in the Content-Type
header. In the case of some of the sources it isn't specified, which
leads to problems when parsing them.

This fixes the failed updates - https://github.com/NixOS/nixos-homepage/runs/2535903129?check_suite_focus=true.

### CODE REVIEW

**Comment by lukegb** [comment]
cc @garbas since I think this is blocking the live site from updating at the moment

The alternative approach here is to just assume that the content is always utf-8, which also seems reasonable and might be better.

**Comment by samueldr** [comment]
@lukegb what would it look like to assume this is always UTF-8?

**Comment by lukegb** [comment]
https://github.com/NixOS/nixos-homepage/blob/master/scripts/update-blog.py#L125

--> `await response.text('utf-8')`

**Comment by samueldr** [comment]
Thanks, won't be my call, but that makes the investigation easier on @garbas for whenever he has the time to look into it :).

**Review by garbas — APPROVED** [review]
Thank you :heart: for taking the time to fix this and sorry that it took so long to review it.

**Pull request merged**
