### PR TITLE
Include manuals + pills as post build step

### PR DESCRIPTION
**Pull request by garbas**
and remove not used files

### CODE REVIEW

**Comment by garbas** [comment]
Still on the TODO list is listing the AMIS

**Comment by thilobillerbeck** [comment]
> [removed a little too much :)](https://github.com/NixOS/nixos-homepage/pull/1225/commits/54e536d12d4869ad518df8ac15e7037f76b39853)

haha, I was just about to complain that dev mode does not work, but this seems to be fixing it :D

**Comment by thilobillerbeck** [comment]
@garbas what about the `site-styles` folder? Did you find anyhting that breaks when removing it? Otherwise I think we can omit it as well.

**Comment by garbas** [comment]
> @garbas what about the `site-styles` folder? Did you find anyhting that breaks when removing it? Otherwise I think we can omit it as well.

`site-styles` folder is removed

**Comment by garbas** [comment]
I think this is now ready for review and potential merge once issues are addressed.

**Review by thilobillerbeck — APPROVED** [review]
looks good

**Pull request merged**
