### PR TITLE
well-known: delegate matrix client/server to matrix.nixos.org

### PR DESCRIPTION
**Pull request by garbas**
We are moving away from EMS and towards self-hosted infrastructure.

cc NixOS/infra#336

Migrated from PR #1218

### CODE REVIEW

**Comment by garbas** [comment]
/cc @mweinelt

Should this PR be merged?

**Comment by mweinelt** [comment]
Depends on the cc-dd PR, so not yet.

**Review by thilobillerbeck — APPROVED** [review]

**Comment by thilobillerbeck** [comment]
Just approved this bc. this will probably merged in the next few hours afaik

**Comment by mweinelt** [comment]
Thank you! Please wait for my confirmation, I'm still waiting to receive the backup.

**Comment by mweinelt** [comment]
Please send it!

**Pull request merged**
