### PR TITLE
Add link to Matrix room

### PR DESCRIPTION
**Pull request by Anton-Latukha**
* You can rephrase as you please.

* Since Matrix room is alive, list it on Community page.

* This contact can also be added to Support page, but that is up to main developers.

### CODE REVIEW

**Comment by grahamc** [comment]
One thing I'm not clear on is why have a separate Matrix room, when the IRC channel is bridged?

**Comment by Anton-Latukha** [comment]
* That is why I started this PR.
    To inform that community info needs sync.
    And how to sync it, is up to the main team.

Since IRC bridged to Matrix, and IRC is still used.

* I propose to say about Matrix first, mention what is bridged with Matrix.

* And then still have IRC, and describe how it is integrated with Matrix, and who lives in IRC. And in near future people will migrate from it anyway. In half a year/year then, IRC room can be gone, if it get's empty.

Also:

* Subreddit still alive, it can be mentioned for now also.

**Comment by edolstra** [comment]
I barely know what Matrix is, so I'm kind of reluctant to declare it as an "official" communication method of the NixOS developer community.

**Comment by Anton-Latukha** [comment]
Matrix is worth to check-out.

It was brewing for years.
Serverless messaging framework and platform.
Now it blows up, and hype starts around it.

It started to work so good, that main investor stopped funding it, because it became such threat to their business (probably).

What I know, that Matrix has: IRC, Slack, Telegram, Glitter, Verto bridges, and probably some unofficial also. That mean that people seamlessly in the same chat, and talk together, from IRC to Matrix and back. And they even don't know that they do that.

That is why migration in going to happen fast.

**Comment by jagajaga** [comment]
@edolstra this is a great service. It's growing nowadays and it's going to be very popular. I vote to accept it.

**Comment by daylightbrightledlight** [comment]
I also vote to accept it.

**Comment by samueldr** [comment]
While I'm a bit miffed that this is splitting the chat-based community a bit, but that's not important. I will argue that we need closure for this PR: do we publicize the existence of that room on the website or not?

I am neither for or against, but I think this PR should be dealt with. Not that it would be a final word forever and ever, but to reduce the backlog.

**Comment by Anton-Latukha** [comment]
As always, because nobody provides topic arguments - I am going to argue with myself.

I argued with myself, changed my position, and here is what I deduced:

#### Why join Matrix-IRC:
Matrix rooms and IRC rooms can be the same space. Due to almost complete transparency.


#### Why rename "NixOS" channel to "NixOS distribution":
1. NixOS distribution and Nix in Linux questions topics and operations are way different.

2. For example - I am NixOS administrator, and more-less know installation process of Nix on other Linux distributions now - but I do not fully know CLI ways to use Nix on other distros, because I use NixOS everywhere. And I am not interested to read non-NixOS chats, more-over starters chats for other Linux-distros. But all that is Nix-related.

3. Mixing NixOS and Nix on Linux creates a collision of methods of application, and confusion for Linux users. I can now go to NixOS room and ask a basic question - an I would get two answers. In terms of how to do it on NixOS and in terms of how to do it on other Linux distributions. Wu wei solution is to make people separate naturally. NixOS channel is for NixOS. Nix channel is for Nix in Linux distributions.

4. If NixOS would be sole to "NixOS distribution" - there would be a spacetime-quality-critical mass for quality participation there. And Nix on Linux would be more for community support of traditional DevOps and onboarding a new community Nix* members.

5. Also, in reality, newcomers to Nix* do not understand the difference between NixOS, Nix package manager, Nix language, Nixpkgs and NixOps, so they can not choose to go to "Nix" or "NixOS" channel. But they can go to "Nix" if they use Nix, and "NixOS distributions" if they installed NixOS. 

But also remember the first argument.

With all these arguments I see the point of renaming "NixOS" room to "NixOS distribution" pretty much proven.  

#### Why split "NixOS distribution" and "NixOS distribution-dev"
There would be more and more people in this Matrix chatroom. And more and more discussion. And it is needed to split development space with bots workflow, and discussions/questions around NixOS.

### Offer:
1. Matrix NixOS room joins NixOS IRC room. And becomes "NixOS distribution". It is a wu wei way to say that it is for NixOS distribution community and contribution, and people with Nix in Linux questions would naturally migrate to Nix channel.
1.a. If there is already too many people in "NixOS distribution" split it to "NixOS distribution" (aka discussion of NixOS questions) and "NixOS distribution-dev" (aka GitHub bots send info here, and contributors talk design/contributions here)
2. Matrix Nix room joins Nix IRC room. This would be a place for wu wei to stream here users of "Nix on non-NixOS". Nix newcomers who try Nix, admins who use Nix on Linux and traditional DevOps who run Kubernetes clusters with Alpine+Nix containers hang-out here. The most enthusiastic NixOS people hang-out here to help traditional Linux people.
3. Core devs have a separate room/means to talk and have more official support. Obviously, this is already true.

**Comment by Anton-Latukha** [comment]
I would reorganize the contribution and the main post.
And then we would see what to implement.

**Comment by Anton-Latukha** [comment]
Closed due to becoming not relevant.

**Pull request closed without merging**
