### PR TITLE
treewide: add mastodon to footer

### PR DESCRIPTION
**Pull request by gilice**
I didn't actually check if the icon works, so don't merge without checking

### CODE REVIEW

**Comment by garbas** [comment]
@fricklerhandwerk did you check if icon is correct? If I remember correctly this PR does not add it.

**Comment by fricklerhandwerk** [comment]
image

**Comment by garbas** [comment]
@fricklerhandwerk that was not the change. The footer does not have an icon.

**Comment by fricklerhandwerk** [comment]
Oh indeed, that Mastodon icon was on the community page.

**Pull request merged**
