### PR TITLE
RSS feeds length and categories fixes

### PR DESCRIPTION
**Pull request by dmchmk**
Hi guys! Recently I've tried to follow NixOS'es news feed, but faced some issues:

1. There was no publicly available link to the feed (found it [in the issues](https://github.com/NixOS/nixos-homepage/issues/1245)). Also mentioned [in this issue](https://github.com/NixOS/nixos-homepage/issues/1195)
2. When I imported feed url to my reader, it was flooded by ~200 entries from beginning of times (year 2004) unlike other feeds usually having 5-10 entries.

And since we're all foss-guys, I've decided to fix issues by myself:)

While fixing length of the rss-feed, I've discovered that [trying to apply](https://github.com/NixOS/nixos-homepage/blob/main/src/pages/blog/%5Bid%5D-rss.xml.js#L20) `filter` to `const` variable isn't a way to get some proper results.

And after making rss-feeds for different categories really differ, I've added three new links on the Blog page under category blocks.

image

### CODE REVIEW

**Comment by thilobillerbeck** [comment]
Hi, thanks for these awesome fixes. I have one small nitpick. Currently the RSS Feed links are below the buttons for category seleciton on mobile as well. I guess it'd be great if they maybe align to the side in the style of the category button (maybe outlined). What do you think about that?
image

**Review by crertel — APPROVED** [review]

**Comment by crertel** [comment]
@thilobillerbeck @tomberek  Can we unblock this? It looks like a reasonable step forward, and we can do a design tweak later if need-be.

**Comment by thilobillerbeck** [comment]
Hi, this is not about blocking. I just did not find any time yet to re-review. I apologize that things move slowly and I try to put some time into this PR as soon as I can.

**Comment by crertel** [comment]
Gotcha, no worries! Sorry if I misread the discussion thread so far. :(

**Comment by dmchmk** [comment]
Hi, @thilobillerbeck, I've updated the mobile view as well

изображение

**Review by thilobillerbeck — APPROVED** [review]
Looks perfect now! Thanks for the great work! <3

**Comment by crertel** [comment]
Looks sharp! Good work y'all!

**Pull request merged**
