### PR TITLE
Commercial page rework

### LINKED ISSUE #451: Commercial support page
- Companies listed in random order, with logo and description what they do in regards to Nix/NixOS
- Collect Testimonials and Success stories

### PR DESCRIPTION
**Pull request by garbas**
This PR tries to refresh the commerical providers page where companies that work with Nix/NixOS are listed. Here is what this PR does:

- list of companies is now randomized every 1h.
- locations, logo and description were added to make a list more interesting.
- updated design
- this page is now reachable from Community page.

## TODO:

- [x] finish the design
- [x] ping companies to collect locations, logo and description

Depends on #669 
Fixes #451

### CODE REVIEW

**Comment by garbas** [comment]
Hey @domenkozar @eamsden @mmahut @ajs124 @rickynils @jagajaga @zimbatm @Ericson2314 @fpletz @qknight !

As you can read in the description of this PR I'm reworking the commerical providers page. I've added a bit more fields then just `name` and `url`. Would you be so kind and send me (in comments here) the following fields about your company:
- locations (where is your company registered and where are your offices)
- logo (link to the logo, please let it be of some normal size)
- description (one twitter lenght)

I will wait for your reply for 2 weeks and then merge it regardless. You are always welcome to update this fields and send the PR.

At the same time, while I have your attention, would you also be interested in writing white paper / success story that you had with Nix/NixOS? I'm only looking if there is enough interest to pursue this.

**Comment by eamsden** [comment]
Black River Software

Location: Ohio, USA
Description:
Black River Software offers custom software development, software architecture consulting, and build and deployment engineering services.
Logo: 
logo

**Comment by zimbatm** [comment]
NumTide Ltd

Location: London, UK
Description: DevOps consulting by Developers.
Logo:
image

**Comment by mmahut** [comment]
@garbas thank you for the work.


Location: We are registered in Tallinn, Estonia with office in Prague, Czech Republic.
Description: `Five Binaries are an infrastructure development company focused on creating customized highly reliable solutions for blockchain-powered industries.`
Logo:
5B_Full_Purple_White_B

**Comment by davidak** [comment]
I think it's important to see what Nix/NixOS service they actually provide. Like when i look for help with fixing a NixOS module or creating a complex package, which one should i choose. There could even be filters for that, like on the https://owncloud.com/partners/ page. Or should i consider all of them capable with anything related to Nix/NixOS?

**Comment by rickynils** [comment]
Immutable Solutions AB

Location: Sweden
Description: Nix specialists helping companies design, develop and deploy systems in a declarative fashion.
Logo: https://immutablesolutions.com/logo.png

**Comment by domenkozar** [comment]
Enlambda

Location: Encorporated in Estonia, otherwise Remote
Description: Turning operational issues into development tasks using Nix since 2013
Logo: https://enlambda.com/images/enlambda.png

**Comment by Ericson2314** [comment]
Logo: 

> [os-logo.zip](https://github.com/NixOS/nixos-homepage/files/5852195/os-logo.zip)

SVG wasn't supported for GitHub attachments, but zip was, so I so archived it. Apologies for the indirection.

Location: 

> New York

Description:

> Software consultancy specializing in Haskell, Nix, curiosity, and innovation.

**Comment by jagajaga** [comment]
Location: Fully remote (registered in Tallinn, Estonia)
Description: Serokell is a custom software engineering company that creates innovative solutions for complex problems. We do software development, consulting, and auditing.

**Comment by jagajaga** [comment]
Location: Fully remote (registered in Tallinn, Estonia)
Description: Serokell is a custom software engineering company that creates innovative solutions for complex problems. We do software development, consulting, and auditing.
Logo-4
Logo-5

**Comment by WilliButz** [comment]
Mayflower

Locations: Registered in Munich, Germany with additional offices in Berlin and Würzburg.
Description: We are Mayflower. We build infrastructure. Declarative & reproducible.
Logo: 
mf-nixflower

**Comment by ajs124** [comment]
- We are registered in Germany, our office is in Stuttgart
- This is our logo: logo [link](https://helsinki-systems.de/wp-content/uploads/2019/09/logo.png)
- Helsinki Systems is your partner for hosting, networks and IT solutions running on NixOS. We have multiple years of NixOS and decades of Linux experience to aid your NixOS integration and administration.

**Pull request merged**
