### PR TITLE
Governance page redesign

### PR DESCRIPTION
**Pull request by garbas**
## Design

- [Governance_desktop.pdf]( https://github.com/NixOS/nixos-artwork/blob/master/www/2020_redesign/Governance/Governance_deskop.pdf)
- [Governance_mobile.pdf]( https://github.com/NixOS/nixos-artwork/blob/master/www/2020_redesign/Governance/Governance_mobile.pdf)

## TODO

- [x] "Learn more" link in RFC process section should be green button (@garbas)
- [x] new image for rfc process, recreate in inkscape (@samueldr)
- [ ]  ‼️ dark blue _diagonal_ background for Teams section (@samueldr)
- [ ] icons for teams (need export from the design @garbas)
- [x] design team listing, font and green button (@garbas)
- [x] add "NixOS foundation" logo missing in mission statement (@samueldr)
- [x] design listing of board members as in design (@garbas)
- [x] design Team pages (@garbas)

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixos-homepage/589)

### CODE REVIEW

**Comment by samueldr** [comment]
>  dark blue diagonal background for Teams section (@samueldr)

This has been *mostly* implemented in #588; 

 * https://github.com/NixOS/nixos-homepage/pull/588/commits/77664271a08fbe188401255be1fcfb89bdc83020
 * https://github.com/NixOS/nixos-homepage/pull/588/commits/250498a6ae15cd6f939166fd65f7ec973ec8a714

I can do the changes if you're not comfortable doing them, once we have that merged in master and master merged in this PR.

**Comment by samueldr** [comment]
>  icons for teams (need export from the design @garbas)

Are the icons from the PDF not okay? If they are I can try extracting them, chances are it'll work just fine since it's not a complicated bit in the PDF.

**Comment by samueldr** [comment]
Given that now #588 lightly depends on this one for the Foundation logo, how should we proceed?

**Comment by garbas** [comment]
I'm going to close this PR and merge this work into #588. Then both pages are going to land at the same time

**Comment by garbas** [comment]
> > icons for teams (need export from the design @garbas)
> 
> Are the icons from the PDF not okay? If they are I can try extracting them, chances are it'll work just fine since it's not a complicated bit in the PDF.

Yes the icons are good from the PDF just I don't know how to extract them.

**Pull request closed without merging**
