### PR TITLE
Add a page for the foundation board

### PR DESCRIPTION
**Pull request by thufschmitt**
The content of the page is taken from the end of https://github.com/NixOS/foundation/blob/04d1492b0963c3f75f66bf7e67526373325e3673/role_and_responsibilities.md.

It would be nice to also get the first part _somewhere_, but I'm not
sure where yet.

### CODE REVIEW

**Comment by thufschmitt** [comment]
cc @NixOS/foundation

**Comment by domenkozar** [comment]
A small note, if you push directly to the branch here, you'll get a deployment link.

**Comment by garbas** [comment]
I'm going to close this PR and open it from branch on this repository.

**Comment by garbas** [comment]
New PR is here (https://github.com/NixOS/nixos-homepage/pull/1105) and preview should be created soon.

**Pull request closed without merging**
