### PR TITLE
Revert "index: add NixCon link to livestream"

### PR DESCRIPTION
**Pull request by RaitoBezarius**
Reverts NixOS/nixos-homepage#1118

NixCon is done!

### CODE REVIEW

**Comment by mweinelt** [comment]
Maybe we show a link to the recordings for a while? Something like

> NixCon is over! Head to the recordings

**Comment by RaitoBezarius** [comment]
Will try to send such a PR. :)

**Comment by garbas** [comment]
@RaitoBezarius And also remove the other banner. There should be only one banner on the front page.

**Comment by garbas** [comment]
I'm reopening and merging this. We can change the banner in the following PRs.

**Pull request merged**
