### PR TITLE
Calendar: init - add links to the common calendars

### PR DESCRIPTION
**Pull request by hsjobeki**
Add the links to our calendars under `/community`

image

@fricklerhandwerk @infinisil

Can we figure out who is responsble for maintaining what i linked here as the "official calendar" ?

Please feel free to make changes.

### CODE REVIEW

**Comment by fricklerhandwerk** [comment]
AFAIK these people currently have write access:
- @edolstra (admin)
- @garbas
- @infinisil
- @tomberek

**Review by fricklerhandwerk — APPROVED** [review]

**Comment by thilobillerbeck** [comment]
Hey, it would have been great if you waited for someone from the marketing team to review this. Unfortunately why I like the change, the layout of the calendar links could definitely be improved. It would be great if it uses a 3 column grid as in the section above.

**Comment by thilobillerbeck** [comment]
Reason for that being that they now look pretty off with a huge amount of whitespace to the right and stretched.

**Comment by thilobillerbeck** [comment]
Everything is resolved now :)

**Pull request merged**
