### PR TITLE
Document how to uninstall on MacOS

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by zimbatm** [comment]
This will be fixed automatically once the linked PR is merged in the nix repo

**Comment by samueldr** [comment]
The link to the installation section now has the required changes. I believe this PR can now be closed (without merging).

I have also commented on the [linked issue](https://github.com/NixOS/nix/issues/1551) to cross-reference and confirm the change isn't needed.

**Comment by zimbatm** [comment]
Nice. Is it possible to group the uninstallation methods in it's own chapter?

 We still need to replace the "You can uninstall Nix simply by running ..." text on the homepage with something and it would be nice to point to a single chapter.

**Comment by garbas** [comment]
closing this this is being tracked under nix repo: https://github.com/NixOS/nix/issues/1551

**Pull request closed without merging**
