### PR TITLE
move search from navigation bar to learn page

### LINKED ISSUE #457: Search "actions" in header can't be used on narrow viewports
The `... for packages` and `... for options` "drop down" items can't be activated using a mouse (unverified for keyboard) when the viewport is narrow. 

image

### PR DESCRIPTION
**Pull request by garbas**
fixes #457

### CODE REVIEW

**Comment by edolstra** [comment]
I'm not so sure about this. The only reason I visit nixos.org is for the options/package search...

**Comment by davidak** [comment]
same

we have the links in the footer and package search on the start page. maybe add options search to a section about nixos (that don't exist yet) on the startpage?

so maybe just remove it from the menu? and put a site search there like people expect

**Comment by edolstra** [comment]
I'd keep it in the navbar. You don't want to have to search for the search feature. If we need to save space in the navbar, it could be done like the Red Hat homepage, which has a search icon in the navbar.

**Comment by garbas** [comment]
I'm going to leave a "search icon" link on the right side (pointing to packages search) just to keep it easier to find. Eventually (any day now) this will point to search.nixos.org where visitor will see that you can search also for nixos options.

**Comment by garbas** [comment]
@davidak 

> we have the links in the footer and package search on the start page. maybe add options search to a section about nixos (that don't exist yet) on the startpage?

I tried and it doesn't look good since it complicated things. There is a link to options search.

> so maybe just remove it from the menu? and put a site search there like people expect

I don't think site search adds value since everybody is already using their own preferred search engine.

**Comment by chrissound** [comment]
I think moving it at the bottom isn't ideal for discover-ability. The whole reason I even knew about the options search is because it was on the front page navigation (otherwise I assumed one just browses the nix source code to figure things out).

Possibly we could link the options search on the package search page? That could also help.

**Pull request merged**
