### PR TITLE
Update the number of packages in index.tt and about.tt

### PR DESCRIPTION
**Pull request by magnetophon**

### CODE REVIEW

**Comment by samueldr** [comment]
Aww, I'm sorry, and that's annoying; `xmllint` being used to lint the HTML source makes it so using `&thinsp;` won't work; it's not valid XML, though it is valid HTML.

```
xmllint --nonet --noout nixpkgs/index.html.tmp
nixpkgs/index.html.tmp:74: parser error : Entity 'thinsp' not defined
40&thinsp;000  packages for the Nix package manager, released under a <a
          ^
make: *** [Makefile:132: nixpkgs/index.html] Error 1
```

The solution is simple; were I a member in this repository I could push over your branch and fix it myself. The fix is to use its decimal-representation as follows.

```diff
diff --git a/nixos/about.tt b/nixos/about.tt
index 656c9c0..f86b9fd 100644
--- a/nixos/about.tt
+++ b/nixos/about.tt
@@ -235,7 +235,7 @@ Here are some highlights of what NixOS currently provides:</p>
 
   <li>NixOS build on the <a href="[%root%]nixpkgs">Nix Packages
   collection</a> (Nixpkgs), which provides Nix expressions for over
-  40&thinsp;000 packages that you can install under NixOS.</li>
+  40&#8201;000 packages that you can install under NixOS.</li>
 
   <li>NixOS has automatic hardware detection: the boot process loads
   kernel modules for all known devices automatically.  It also has
diff --git a/nixpkgs/index.tt b/nixpkgs/index.tt
index 81ed35c..03f312c 100644
--- a/nixpkgs/index.tt
+++ b/nixpkgs/index.tt
@@ -1,7 +1,7 @@
 [% WRAPPER layout.tt title="The Nix Packages collection" menu='nixpkgs' %]
 
 <p>The <em>Nix Packages collection</em> (Nixpkgs) is a set of over
-40&thinsp;000  packages for the Nix package manager, released under a <a
+40&#8201;000  packages for the Nix package manager, released under a <a
 href="https://github.com/NixOS/nixpkgs/blob/master/COPYING">permissive
 MIT/X11 license</a>.  It supports the following platforms (though not
 all packages work on all platforms):</p>

```

When done, the pages will be able to be built, here's how the fragment looks like.

image

**Comment by magnetophon** [comment]
Thanks for the steamcourse XML!

**Comment by magnetophon** [comment]
Any news?

**Comment by samueldr** [comment]
I don't have any rights over this repository, and its activity volume is pretty low, sometimes making things fly under the radar. AFAIK this repository generally gets activity with merging PRs on week days. In case no activity happens by Thursday, do ask back, I'll try to get hold of someone who can do something here.

**Comment by magnetophon** [comment]
Thanks a lot!

**Comment by edolstra** [comment]
Thanks!

**Pull request merged**
