### PR TITLE
Move shell prompts to the text

### PR DESCRIPTION
**Pull request by jtojnar**
They are part of the screen output just like the command or the printout.

Used `shell-prompt` class to avoid collision with Docbook’s prompt.

Screenshot:

image

### CODE REVIEW

**Comment by jtojnar** [comment]
Thannks. However, the space should be part of the `prompt`, otherwise it gets copied and then the command will not be saved into shell history.

**Comment by garbas** [comment]
ah right, i'll fix it asap.

**Comment by jtojnar** [comment]
Looks like this was forgotten in the new design.

**Comment by garbas** [comment]
@samueldr ping

**Comment by Majsvaffla** [comment]
I installed nix today, following https://nixos.org/download.html#nix-install-windows, and noticed the prompt character was also selectable. I wanted to open an issue or MR myself but then I found this one. Since this one was merged almost three years ago, how come the changes havn't made it to the live website yet?

**Comment by jtojnar** [comment]
Looks like the [stylesheet](https://github.com/NixOS/nixos-homepage/blob/7614bc91461a9239b2f2bb5faf848918613a1a0c/css/nixos-site.css#L181-L184) where the prompt is made unselectable is no longer used? Probably needs to be moved to https://github.com/NixOS/nixos-common-styles

**Comment by Majsvaffla** [comment]
> Looks like the [stylesheet](https://github.com/NixOS/nixos-homepage/blob/7614bc91461a9239b2f2bb5faf848918613a1a0c/css/nixos-site.css#L181-L184) where the prompt is made unselectable is no longer used? Probably needs to be moved to https://github.com/NixOS/nixos-common-styles

Alright, I opened an MR over there 🙂

**Pull request merged**
