### PR TITLE
manual: do not use normal whitespace in code

### PR DESCRIPTION
**Pull request by jtojnar**
It breaks prompts among other things:
https://nixos.org/manual/nixpkgs/stable/#sec-patches

### CODE REVIEW

**Comment by samueldr** [comment]
(Note to self) fix `pre code`

**Comment by samueldr** [comment]
Yep, [it was part of the previous code](https://github.com/NixOS/nixos-homepage/blob/461c7622cc6cfa6a199c1c552c703e907544b841/css/nixos-site.css#L381-L391).

**Comment by jtojnar** [comment]
Might be caused by a change in the syntax highlighter then? Because it seems to wrap the prompts in `<code>`.

**Comment by samueldr** [comment]
Ah, I was updating the comment, sorry :)

The produced DOM is equivalent, so I don't think so.

The reason is that bootstrap added:

```
code {
   white-space: nowrap;
}
```

By default.

**Pull request merged**
