### PR TITLE
Add nix community values

### LINKED ISSUE #1534: Add Nix Community Values
In recent months, the [Nix Constitutional Assembly](https://github.com/nixos/nix-constitutional-assembly) has gathered feedback from around the community and established [these Nix Community Values](https://github.com/NixOS/nix-constitutional-assembly/blob/bbbfb8fb26b77e9e8e4bfddc8c376c6853330643/values.md). The drafts were previously [announced on Discourse](https://discourse.nixos.org/t/nix-community-values-draft-for-feedback-before-finalisation/49950), but are now finalised as the first version. How these values get evolved in the future will be defined in the Nix Governance Constitution, whose [draft is published](https://discourse.nixos.org/t/nix-governance-constitution-draft-for-feedback/51373) and open for feedback. So for now they should remain exactly as is.

[The finalised version of the Nix Community Values](https://github.com/NixOS/nix-constitutional-assembly/blob/bbbfb8fb26b77e9e8e4bfddc8c376c6853330643/values.md) should now be added to the website, somewhere where they can easily be found via the [Community](https://nixos.org/community/) page, ideally with anchored headings. This issue is there to track this.

Ping @NixOS/nix-constitutional-assembly @NixOS/marketing-team

### PR DESCRIPTION
**Pull request by crertel**
Closes #1534 .

This is a first rough cut to get us talking--it wasn't clear to me if @infinisil was suggesting that this be on the community page or merely linked to, so I figured we could try something and see how we felt.

image
image

### CODE REVIEW

**Comment by infinisil** [comment]
This is looking great, thank you!

The only extra optional thing I'd be interested in is to have anchors that can be clicked and linked to, but I'm not sure how easy that is to implement. Definitely not a blocker though :)

I can't merge this myself, but I'm guessing the marketing team will get to this eventually.

**Comment by thilobillerbeck** [comment]
> This is looking great, thank you!
> 
> The only extra optional thing I'd be interested in is to have anchors that can be clicked and linked to, but I'm not sure how easy that is to implement. Definitely not a blocker though :)
> 
> I can't merge this myself, but I'm guessing the marketing team will get to this eventually.

already saw this, but I wanted to test how everything goes layout wise on mobile. Had no time to review yet, but looks good so far. :)

**Review by thilobillerbeck — CHANGES_REQUESTED** [review]
image

So I finally had some time to review. First of all thank you for helping display these really important guidelines on our homepage. <3

I have two small gripes with the current state, the first one is that the clickable headlines, while pretty cool in function, now break with the rest of the headlines in regards to color and styling. Maybe putting some anchor Icon next to them would fit more in line with the rest of the community page. Secoundly the quotation boxes could use some less padding on mobile, I guess they would still be seen as such and the text can have a bit more breathing room.

Btw. should we maybe just dedicate a dedicated page to the values instead of blowing up the community page? Would be interested to hear your opinion on that. :)

**Comment by chromaticbear** [comment]
> Would be interested to hear your opinion on that. :)

Given the evolution of the values, I figure we might as well post them up front before directing people into spaces.

**Comment by crertel** [comment]
Went ahead and added a dedicated values page.

**Review by thilobillerbeck — APPROVED** [review]
applie some small tweaks but now its alright, thanks for your contribution and thanks for your patience <3

**Comment by infinisil** [comment]
Thank you, @crertel and @thilobillerbeck! :heart:

**Pull request merged**
