### PR TITLE
Mention 'nix search' on search page

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by edolstra** [comment]
`nix` is an experimental command (it even needs to be enabled explicitly using a flag in Nix 2.4) so we probably shouldn't advertise it on the website.

**Comment by raboof** [comment]
oh, sorry, it was recommended to me on IRC and I really like it ;). What would be the non-experimental alternative?

**Comment by edolstra** [comment]
`nix-env -qa`

**Comment by raboof** [comment]
meh, that's way less convenient... nevermind I guess.

**Pull request closed without merging**
