### PR TITLE
fix mastodon icon in footer

### PR DESCRIPTION
**Pull request by garbas**

### CODE REVIEW

**Comment by drupol** [comment]
Fixed in https://github.com/NixOS/nixos-common-styles/pull/28

**Comment by infinisil** [comment]
@garbas Please disallow direct pushes to master and require passing CI checks for this repo so this can't happen again

**Comment by drupol** [comment]
@infinisil Can you merge https://github.com/NixOS/nixos-common-styles/pull/28 to fix the black Mastodon icon now?

**Comment by drupol** [comment]
OK, then there will be a black Mastodon icon on nixos.org until ...

**Pull request merged**
