### PR TITLE
packages: include unfree and broken packages in the search index

### PR DESCRIPTION
**Pull request by LnL7**
This should help a little bit with https://github.com/NixOS/nixpkgs/issues/17126, hopefully a some more users will find packages because of this.

### CODE REVIEW

**Comment by ToxicFrog** [comment]
It looks like, due to a separate issue with the JS, such packages won't be clearly marked as "unfree", since license information for most (all?) packages is not displayed. This should be a fairly easy fix (and in fact FIXME #49 already exists for it) to look for `info.meta.license.fullName` if `info.meta.license` is an Object rather than a String.

**Comment by edolstra** [comment]
Sorry, but Nixpkgs is intended as a free software distribution, so it should not promote the availability of unfree packages. It also shouldn't show broken packages unless they are conspicuously marked as broken.

**Comment by LnL7** [comment]
The reason for this change is that somebody tried to package sublime text, and discovered after 3 hours that we already have it.

**Comment by copumpkin** [comment]
@edolstra there's a difference between promoting and actively hiding. All we want is a good user experience, and hiding existing work from users because of a philosophical stance doesn't seem helpful in the long run. It causes wasted work, as @LnL7 mentioned, and also causes people to incorrectly conclude that Nix and nixpkgs is less mature and capable than it really is.

It seems possible to at least openly acknowledge that we have the packages in the system while still not building or distributing them over Hydra and getting people to opt into installing them, right? I'm not looking for magic "oh shit my system is full of unfree software how did that happen???" situations, but there has to be a happy medium between forcing people to clone and grep nixpkgs to find out that we have e.g., Spotify or Steam and installing it on their system by default, right?

**Comment by ToxicFrog** [comment]
@edolstra I'm not convinced that showing them in the index clearly marked as "nonfree" counts as "promoting" them; if you're that concerned, maybe make it an opt-in "show packages with nonfree licenses" tickbox on the page somewhere rather than making it on by default. Even debian, who are fairly hardcore about this, [don't go so far as to completely hide nonfree packages from the index](https://packages.debian.org/search?keywords=steam&searchon=names&suite=stable&section=all). Neither does SUSE, although they relegate nonfree packages to a separate repo.

I do agree that this shouldn't be merged until displaying package licenses is fixed.

**Comment by ToxicFrog** [comment]
Also, even if they are listed in the index and someone doesn't realize they're nonfree, there's still no chance of accidentally installing nonfree software, because as soon as you try it'll error out and tell you to enable `allowUnfree` if you really mean to do this.

**Comment by jcrben** [comment]
@edolstra how would you feel about hinting to users that an unfree package exists, especially if they get zero results? that's a suggestion by @alexfmpe over at https://github.com/NixOS/nixpkgs/issues/17126#issuecomment-369242742

**Comment by davidak** [comment]
I think an option to "Show proprietary packages" like in https://github.com/NixOS/nixos-homepage/pull/78 would be a good solution. Maybe with tooltip to clearify what free software is and why you might not want to use proprietary software.

**Comment by samueldr** [comment]
Hi, I've been watching the thread here for a while.

I have a solution I have been working off and on (mostly off) for that problem, which is a re-implementation of the packages searcher with more features, including regex search, switching channels and showing unfree packages.

Here's a demo: https://nix.samueldr.com/explorer/

I haven't yet made "official moves" to get this on the website since I still need to

 1. Cleanup the code.
 1. Integrate it into the website build.
 1. Misc minor improvements.

The code isn't *bad*, but I want to at least put my eyeballs on every lines once more. [The code isn't hidden away](https://github.com/samueldr/nixos-packages-explorer).

Let's make this comment a commitment to try harder to upstream this effort.

**Comment by davidak** [comment]
@samueldr great!

This still don't fixes the issue i just commented in https://github.com/NixOS/nixos-homepage/issues/57.

https://nix.samueldr.com/explorer/?channel=nixos-unstable&page=1&query=screen&unfree=true

Also, regex is not something a normal user is able to use. Instead it should not be necessary to use it.

**Comment by samueldr** [comment]
Let's say I can subtly insert a way to permalink to a particular attribute :sweat_smile:, as this would be a better experience than using a regex. Using such link could also unfold the result row automatically.

**Comment by garbas** [comment]
I'm closing this PR due being inactive and also since many things changes since this was opened. we will probably continue on this topic here -> https://github.com/NixOS/nixos-homepage/pull/300

**Pull request closed without merging**
