### PR TITLE
updated sources of security information; removed a dead key

### PR DESCRIPTION
**Pull request by ekalosak**
Resolves [issue 251](https://github.com/NixOS/nixos-homepage/issues/251) re: outdated security page.

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @rbvermaa

**Comment by ekalosak** [comment]
Out of curiosity, what's the process for merging PRs after review?

**Comment by domenkozar** [comment]
Let's wait for Rob a couple of days and then merge :)

**Comment by Ekleog** [comment]
@domenkozar Is 10 days “a couple of days”? :)

**Pull request merged**
