### PR TITLE
Build Github pages for pull requests

### PR DESCRIPTION
**Pull request by LoveIsGrief**
Since this project generates a static site, one can take advantage of [Github Pages](https://pages.github.com/) to host it. In the case of this PR, it introduces the ability to review the the static site generated by pull requests.

Another benefit is that modifications need not require the lengthy installation of `nix` (related to #833)

# How it works

The PR will build the static site, modify the `pages` branch by adding a new directory with the name of the PR branch in the `/pages/` folder and updating `/index.html` with the list of directories therein, then finally push it. This allows for PRs to reviewed by navigating to the github pages URL (example below). 

# Required setup

 - Create `pages` branch
 - Use `pages` branch as the [source for Github Pages](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) on this project

# Example result

LoveisGrief/nixos-homepage#1 showcases the [result](https://loveisgrief.github.io/nixos-homepage/)

# Possible pitfalls

**Branch name collision**

Since the branch name is used I'm not sure what the source branch names look like for forked repos. PRs with the same branch name might overwrite each other, but I'm not sure. I used [`github.head_ref`](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context). Using `github.ref_name` gave me `1/merge` which I assume is the PR number with `/merge` (?).

### CODE REVIEW

**Comment by garbas** [comment]
Thank you for putting the time into this, but the preview is already generated (published via Netlify) if branch originates from current repository. This used to be a limitation of GitHub at some point, but it looks like we could also enable it also for other PRs where branch does not originates from this repo.

**Comment by garbas** [comment]
@LoveIsGrief Not correct. You don't need to a Netlify account to preview a website. You can either run a local development server or you run `nix-build` and serve `./result` folder locally (which what local development server is doing).

**Comment by LoveIsGrief** [comment]
I'm thinking more of the PR review. Someone makes a PR, says they vertically centered a div. You want to have a look at the result.

You can either pull the branch and preview it locally, or (with my PR) go to the github page and see it live. Also, if you're on your phone or on the way and would like to have a look, there won't be a need to wait till you have access to a machine with nix.

Right now, that isn't possible, even if you were to remove the condition on the CI step that publishes to netlify. More work would probably have to be done, no? 
This PR removes the netlify dependency for PRs.

**Comment by garbas** [comment]
As I said above, the preview is already created. But at the time github was missing some features regarding security we are not allowing just anybody to create a preview, just for PRs that are created from a branch on this repo. Now that GitHub has much better security story there we could consider enabling this also for other PRs.

There is no need to involve GitHub pages since Netlify provides this functionality for us.

**Pull request closed without merging**
