### PR TITLE
Change many HTTP links to HTTPS

### PR DESCRIPTION
**Pull request by 8573**
Change many HTTP URLs to use HTTPS instead, where the resource to which
the URL refers is available via HTTPS.

### CODE REVIEW

**Comment by domenkozar** [comment]
Thanks!

**Comment by 8573** [comment]
Thanks for merging!

**Comment by danbst** [comment]
@8573 how did you test this?

**Comment by 8573** [comment]
@danbst: By opening each of the links in Chromium.

**Comment by danbst** [comment]
I hoped you have sometimes automation... but ok

**Pull request merged**
