### PR TITLE
Integrate nix.dev tutorials as a flake

### PR DESCRIPTION
**Pull request by edibopp**
was #484, now there should be a preview ;)

----

This replaces the current manually copy-pasted tutorials by the same content from https://github.com/domenkozar/nix.dev. This is a pretty selective extraction of individual guides from https://nix.dev.

Further extensions:

    syntax highlighting via pygments as already generated by sphinx
    integration of more guides

---
This change is [Reviewable](https://reviewable.io/reviews/nixos/nixos-homepage/486)

### CODE REVIEW

**Comment by garbas** [comment]
The last example 

2020-06-22-133444_1880x730_scrot

shows a bit of unnecessary indent

**Comment by garbas** [comment]
/me merged latest master and resolved conflicts

**Comment by davidak** [comment]
The page title is not shown correctly in the browser:

Screenshot from 2020-09-05 03-27-24

There is a white space in front of `,`, `.` and `:` in many cases!

Screenshot from 2020-09-05 03-31-56

Screenshot from 2020-09-05 03-34-05

maybe a problem with the import?

rest looks good. haven't read the actual content.

**Review by davidak — CHANGES_REQUESTED** [review]
The page title is not shown correctly in the browser:

Screenshot from 2020-09-05 03-27-24

There is a white space in front of `,`, `.` and `:` in many cases!

Screenshot from 2020-09-05 03-31-56

Screenshot from 2020-09-05 03-34-05

maybe a problem with the import?

rest looks good. haven't read the actual content.

**Comment by garbas** [comment]
@davidak nice catch ... should be fixed now.

**Pull request merged**
