### PR TITLE
Add News RSS feed to website

### PR DESCRIPTION
**Pull request by noffle**
Hi, this is one of my first NixOS PRs. :wave:

This PR addresses https://github.com/NixOS/nixos-homepage/issues/15 and is broken up into 3 logical pieces:

1. Replaces the `<year>/<month>/<day>` tags in `news.xml` with the single tag `<pubDate>`. This format is easy to parse in XSLT 1.0 (no date functions) using only substrings, and happens to also be the expected format for RSS 2.0.

2. Adds an XSLT transform, `news-rss.xsl` that produces the RSS 2.0 feed `news-rss.xml` from `news.xml`.

3. Updates `index.tt` to include
  i. a `<link>` tag for the RSS feed
  ii. an RSS icon + link to the RSS feed beside the "News" heading
  iii. an RSS icon + link to the RSS feed beside the "Blog Posts" heading

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @edolstra

**Comment by domenkozar** [comment]
Thanks!

**Comment by edolstra** [comment]
Thanks, merged. However there are two issues:
* The `<description>` elements contain HTML, which is apparently not allowed. So the generated RSS doesn't validate according to https://validator.w3.org/feed/, and the descriptions don't show up in Firefox.
* `blogs.xml` is very big because it contains the complete contents of every blog post, so it may not be very suited as a feed.

**Comment by noffle** [comment]
Thank you, @edolstra. I also appreciate the feedback:

1. You're right: all of the HTML is escaped in e.g. `blogs.xml`. It's a side effect of us using XML for the news data but in inlining HTML /wo escaping we're treating it like XML data. I'll see how hard this is to do in XLST.
2. I'd be fine with capping `blogs.xml` at, say, 20-25 entries.

**Pull request merged**
