### PR TITLE
Rework Community links

### PR DESCRIPTION
**Pull request by nat-418**
This PR reworks the links section of the community page, per discussion in #1438.

### CODE REVIEW

**Comment by thilobillerbeck** [comment]
I'm in all honesty not sure that this was the consensus of the discussion 😅

**Comment by nat-418** [comment]
> I'm in all honesty not sure that this was the consensus of the discussion 😅

This is a draft PR with one commit. When I have time later I am going to add more.

**Comment by nat-418** [comment]
So the latest commit basically achieves what I think should actually be done. I am going to try and add stuff other people wanted in the issue discussion, but I think per @samueldr and @mweinelt's concerns it might be worth considering just stopping here. So I am going to unmark as Draft so folks can leave reviews. I am not wedded to the wording, I just thought some of the language on the page was redundant.

**Comment by nat-418** [comment]
@thilobillerbeck per @infinisil's recommendation in the Matrix room, I added a link to the ["Get in Touch"](https://wiki.nixos.org/wiki/Get_In_Touch) Wiki page which has more unofficial resources on it and is pretty easy to add to. Does that work for you? I'm happy to change the wording of some of the other edits I made, it just seemed not necessary to have some of the verbiage after the simplification.

**Comment by tomberek** [comment]
Closing. Existing PR (https://github.com/NixOS/nixos-homepage/pull/1444) made progress to resolve the question. Further PRs can break the sections apart if necessary. We can accept a PR having "official accounts" be distinct from "unofficial spaces".

**Comment by nat-418** [comment]
> Closing. Existing PR (#1444) made progress to resolve the question. Further PRs can break the sections apart if necessary. We can accept a PR having "official accounts" be distinct from "unofficial spaces".

I don't know why you call it "existing PR" when my PR was opened first, which is why it is PR number #1441 and the PR you decided to review and merge instead was PR #1444.

**Pull request closed without merging**
