### PR TITLE
migrate information on documentation team to GitHub

### PR DESCRIPTION
**Pull request by fricklerhandwerk**
depends on https://github.com/NixOS/nix.dev/pull/346

### CODE REVIEW

**Review by garbas — CHANGES_REQUESTED** [review]
I believe this adds more things that what is mentioned in the title of the PR. I'm not sure this is intentional, but it would be nice to split some things out in different PRs.

**Comment by fricklerhandwerk** [comment]
Sorry, that was some random Git noise.

I know this thing looks super ugly, but I prefer we fix-forward the systemic issues instead. @LucPerkins told me he can probably spend some serious time on the website, so there is a chance for progress there.

**Comment by garbas** [comment]
As with #907 lets list basic information on the team page and then point out elsewhere for the details.

**Comment by fricklerhandwerk** [comment]
Okay, I'll revert it to present a bare minimum: purpose, contacts, and a link to the team repository.

**Comment by garbas** [comment]
@fricklerhandwerk Thank you! I understand is not a perfect situation, but hopefully we get there soon.

**Comment by fricklerhandwerk** [comment]
@garbas done, please check if that's okay for you.

**Review by garbas — APPROVED** [review]

**Pull request merged**
