### PR TITLE
Format/init

### PR DESCRIPTION
**Pull request by hsjobeki**
Adds formatting checks to the CI

with using "prettier" with "prettier-plugin-astro"

Locally developers can run:

`nix run .#format` to format the src directory`

Alternatively / Additionally:

Use any LSP that has `prettier` support.
 
or run:

`npm run format`
`npm run format:check`

Ci executes:

`nix build .\#checks.x86_64-linux.format`

Which fails if the formatting is not in the required format which will ensure the format stays consistent.

### CODE REVIEW

**Comment by tomberek** [comment]
I've not looked at the workflow yet, but likely would want a .git-blame-ignore-revs

**Comment by hsjobeki** [comment]
> I've not looked at the workflow yet, but likely would want a .git-blame-ignore-revs

- [x] Added .git-blame-ignore-revs

**Review by thilobillerbeck — CHANGES_REQUESTED** [review]
Looks good :+1: could you update your branch to the current state of `main`? Then I'll merge it. :)

**Review by tomberek — APPROVED** [review]
Looks good overall. Let's just do a conflict resolution.

**Review by thilobillerbeck — APPROVED** [review]

**Pull request merged**
